name: build and push docker image

on:
  workflow_run:
    workflows: ["Node.js.yml"]
    types:
      - completed
    branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        # The if conditional checks if the workflow_run event was successful before running the job.

        steps:
        - uses: actions/checkout@v2
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
              context: .
              push: true
              tags: distinctugo/advanced_github_actions:latest
        